id: IDD74AB7E
legacy_id: P001843
ocr_import_info:
  bdrc_scan_id: W14615
  source: bdrc
  ocr_info:
    timestamp: '2020-03-31T11:56:53'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T14:43:47.230289+00:00'
last_modified: 2022-08-30 22:44:22.665190
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W14615
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW14615
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོའི་རང་རྣམ།
  author: ཁྲི་བྱང ༠༣་བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6187183830001569
  ocr_word_median_confidence_index: 0.7099999785423279
quality: null
bases:
  I3491:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3491
      total_pages: 560
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I3491.txt
    statistics:
      ocr_word_median_confidence_index: 0.7099999785423279
      ocr_word_mean_confidence_index: 0.6187183830001569
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
