id: P001843
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W14615
  title: བློ་བཟང་ཡེ་ཤེས་བསྟན་འཛིན་རྒྱ་མཚོའི་རང་རྣམ
  author: ''
  volumes:
    727de02876ad4f0e9cf34265bac859a5:
      image_group_id: I3491
      title: ''
      volume_number: 1
      total_pages: 560
      base_file: v001.txt
